# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etcdedit < Formula
  desc "Directly edit Kubernetes resources stored in etcd"
  homepage "https://github.com/ahmetb/etcdedit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ahmetb/etcdedit/releases/download/v0.1.0/etcdedit_darwin_amd64.tar.gz"
      sha256 "ff72239bfc292fc289d96bdc9dec4e6a964d15d8a2a865d9484d6c91ddd5c6ff"

      define_method(:install) do
        bin.install "etcdedit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ahmetb/etcdedit/releases/download/v0.1.0/etcdedit_darwin_arm64.tar.gz"
      sha256 "f1b04a9a2737ee3f300d84b26e1a40a94173c8fadfeaf54fe88fc08079e060fb"

      define_method(:install) do
        bin.install "etcdedit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahmetb/etcdedit/releases/download/v0.1.0/etcdedit_linux_amd64.tar.gz"
      sha256 "654a698e0fb4cd6ebe12a0dc322d6a7f7b96cc19c0d5863a06c41dae2b4a02cc"
      define_method(:install) do
        bin.install "etcdedit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ahmetb/etcdedit/releases/download/v0.1.0/etcdedit_linux_arm64.tar.gz"
      sha256 "3ffceb652a99869a08ddadcf6869ff6ff524b3c0eba695488081a12aa992761e"
      define_method(:install) do
        bin.install "etcdedit"
      end
    end
  end

  test do
    system "#{bin}/etcdedit", "--help"
  end
end
